# Generated by Django 5.2.1 on 2025-07-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_cambiar_experiencia_a_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
