# Generated by Django 5.2.2 on 2025-07-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_cambiar_experiencia_a_choices'),
        ('usuarios', '0011_password_reset_fields'),
    ]

    operations = [
    ]
