# Generated by Django 5.2.2 on 2025-07-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_merge_20250721_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
