# Generated by Django 5.2.1 on 2025-07-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_interesado_foto_perfil'),
        ('usuarios', '0013_alter_vacante_fecha_limite'),
    ]

    operations = [
    ]
