# Generated by Django 5.2.2 on 2025-08-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_vacante_fecha_limite'),
        ('usuarios', '0014_agregar_campos_ubicacion'),
    ]

    operations = [
    ]