# Generated by Django 5.2.2 on 2025-08-05 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_merge_20250805_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos_Postales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.IntegerField(unique=True)),
                ('estatus', models.SmallIntegerField(default=1)),
                ('alta_fecha', models.DateField(auto_now_add=True)),
                ('alta_hora', models.TimeField(auto_now_add=True)),
                ('modificacion_fecha', models.DateField(auto_now=True)),
                ('modificacion_hora', models.TimeField(auto_now=True)),
                ('id_capturo', models.SmallIntegerField(default=1)),
                ('id_modifico', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Código Postal',
                'verbose_name_plural': 'Códigos Postales',
                'db_table': 'codigos_postales',
            },
        ),
        migrations.CreateModel(
            name='Delegaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegacion', models.CharField(max_length=100)),
                ('estatus', models.SmallIntegerField(default=1)),
                ('alta_fecha', models.DateField(auto_now_add=True)),
                ('alta_hora', models.TimeField(auto_now_add=True)),
                ('modificacion_fecha', models.DateField(auto_now=True)),
                ('modificacion_hora', models.TimeField(auto_now=True)),
                ('id_capturo', models.SmallIntegerField(default=1)),
                ('id_modifico', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Delegación',
                'verbose_name_plural': 'Delegaciones',
                'db_table': 'delegaciones',
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('estatus', models.SmallIntegerField(default=1)),
                ('alta_fecha', models.DateField(auto_now_add=True)),
                ('alta_hora', models.TimeField(auto_now_add=True)),
                ('modificacion_fecha', models.DateField(auto_now=True)),
                ('modificacion_hora', models.TimeField(auto_now=True)),
                ('id_capturo', models.SmallIntegerField(default=1)),
                ('id_modifico', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='Tipos_Asentamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asentamiento', models.CharField(max_length=50)),
                ('estatus', models.SmallIntegerField(default=1)),
                ('alta_fecha', models.DateField(auto_now_add=True)),
                ('alta_hora', models.TimeField(auto_now_add=True)),
                ('modificacion_fecha', models.DateField(auto_now=True)),
                ('modificacion_hora', models.TimeField(auto_now=True)),
                ('id_capturo', models.SmallIntegerField(default=1)),
                ('id_modifico', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Tipo de Asentamiento',
                'verbose_name_plural': 'Tipos de Asentamientos',
                'db_table': 'tipos_asentamientos',
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=50)),
                ('estatus', models.SmallIntegerField(default=1)),
                ('alta_fecha', models.DateField(auto_now_add=True)),
                ('alta_hora', models.TimeField(auto_now_add=True)),
                ('modificacion_fecha', models.DateField(auto_now=True)),
                ('modificacion_hora', models.TimeField(auto_now=True)),
                ('id_capturo', models.SmallIntegerField(default=1)),
                ('id_modifico', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'zonas',
            },
        ),
        migrations.CreateModel(
            name='Zonas_Regionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona_regional', models.CharField(max_length=50)),
                ('estatus', models.SmallIntegerField(default=1)),
                ('alta_fecha', models.DateField(auto_now_add=True)),
                ('alta_hora', models.TimeField(auto_now_add=True)),
                ('modificacion_fecha', models.DateField(auto_now=True)),
                ('modificacion_hora', models.TimeField(auto_now=True)),
                ('id_capturo', models.SmallIntegerField(default=1)),
                ('id_modifico', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Zona Regional',
                'verbose_name_plural': 'Zonas Regionales',
                'db_table': 'zonas_regionales',
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100)),
                ('estatus', models.SmallIntegerField(default=1)),
                ('alta_fecha', models.DateField(auto_now_add=True)),
                ('alta_hora', models.TimeField(auto_now_add=True)),
                ('modificacion_fecha', models.DateField(auto_now=True)),
                ('modificacion_hora', models.TimeField(auto_now=True)),
                ('id_capturo', models.SmallIntegerField(default=1)),
                ('id_modifico', models.SmallIntegerField(default=1)),
                ('catalogo_delegacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.delegaciones')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipios',
            },
        ),
        migrations.AddField(
            model_name='delegaciones',
            name='catalogo_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.zonas'),
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=100)),
                ('estatus', models.SmallIntegerField(default=1)),
                ('alta_fecha', models.DateField(auto_now_add=True)),
                ('alta_hora', models.TimeField(auto_now_add=True)),
                ('modificacion_fecha', models.DateField(auto_now=True)),
                ('modificacion_hora', models.TimeField(auto_now=True)),
                ('id_capturo', models.SmallIntegerField(default=1)),
                ('id_modifico', models.SmallIntegerField(default=1)),
                ('catalogo_codigo_postal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.codigos_postales')),
                ('catalogo_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.estados')),
                ('catalogo_municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.municipios')),
                ('catalogo_tipo_asentamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.tipos_asentamientos')),
                ('catalogo_zona_regional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.zonas_regionales')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidades',
                'indexes': [models.Index(fields=['catalogo_codigo_postal', 'estatus'], name='localidades_catalog_66f31a_idx'), models.Index(fields=['catalogo_municipio', 'estatus'], name='localidades_catalog_235de3_idx'), models.Index(fields=['catalogo_estado', 'estatus'], name='localidades_catalog_273f79_idx')],
            },
        ),
    ]