# Generated by Django 5.2.2 on 2025-11-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_codigos_postales_delegaciones_estados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='max_postulaciones_por_consulta',
            field=models.IntegerField(choices=[(5, '5'), (10, '10'), (20, '20'), (50, '50')], default=20, help_text='Número máximo de postulaciones que se pueden consultar por vez'),
        ),
    ]
