# Generated by Django 5.2.2 on 2025-08-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_codigos_postales_delegaciones_estados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='max_postulaciones_por_consulta',
            field=models.IntegerField(default=10),
        ),
    ]
