# Generated by Django 5.2.8 on 2025-11-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_vacante_max_postulaciones_por_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacante',
            name='max_postulantes',
            field=models.IntegerField(choices=[(5, '5'), (10, '10'), (20, '20'), (50, '50')], default=5),
        ),
    ]
