# Generated by Django 5.2.8 on 2025-11-27 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_alter_vacante_max_postulantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacante',
            name='max_postulaciones_por_consulta',
        ),
    ]
